# Image Processing with NumPy (Indexing & Slicing in Action)

In [3]:
import numpy as np

def image_processing():
    # Creating a grayscale image using a 2D NumPy array
    image = np.random.randint(0, 256, (5, 5), dtype=np.uint8)

    print("Original Image:\n", image)

    # Slicing a portion of the image
    cropped = image[1:4, 1:4]
    print("Cropped Section:\n", cropped)

    # Inverting colors
    inverted_image = 255 - image
    print("Inverted Image:\n", inverted_image)

# Call the function
image_processing()


Original Image:
 [[ 31 106 171  66 114]
 [255  89  93  36 230]
 [231 206   4 164  17]
 [124  10  74  61 219]
 [240  44 121 136 121]]
Cropped Section:
 [[ 89  93  36]
 [206   4 164]
 [ 10  74  61]]
Inverted Image:
 [[224 149  84 189 141]
 [  0 166 162 219  25]
 [ 24  49 251  91 238]
 [131 245 181 194  36]
 [ 15 211 134 119 134]]
