# Basic Operations with 1D and 2D NumPy Arrays

In [8]:
# Import numpy library
import numpy as np
# Create Global 1D and 2D arrays

arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def basic_operations():
  # Print 1D and 2D array outputs

  print("1D Array:", arr_1d)
  print("2D Array:\n", arr_2d)

  # Basic Array Operations

  print("Sum of 1D Array:", np.sum(arr_1d))
  print("Mean of 2D Array:", np.mean(arr_2d))
  print("Transpose of 2D Array:\n", arr_2d.T)

basic_operations()

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of 1D Array: 15
Mean of 2D Array: 5.0
Transpose of 2D Array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
