In [5]:
#Function as first class objects

def greet():
  print("Hello, I am under the water!")

say_hello = greet

say_hello()

Hello, I am under the water!


In [6]:
# Passing func as an arguments
def add(x,y):
  return x + y

def operate_numbers(f,a,b):
  return f(a,b)

result = operate_numbers(add,2,3)
print(result)

5


In [8]:
#Returning functions from other functions

def multiplier(factor):
  def multiply(num):
    return num * factor
  return multiply

double = multiplier(2)
triple = multiplier(3)

print(double(5))
print(triple(5))

10
15


In [9]:
# recursive function

def factorial(n):
  if n == 0:
    return 1
  else:
    return n * factorial(n-1)

print(factorial(5))

120


In [11]:
#Doc strings

def calculator(values):
  """This is a calculator function"""
  pass



In [13]:
help(calculator)

Help on function calculator in module __main__:

calculator(values)
    This is a calculator function



In [15]:
#local and global variables

#local variable

def calculator():
  a = 10
  b = 20
  print("Addition of two numbers are:", a+b)

calculator()

Addition of two numbers are: 30


In [20]:
#Global variable
a = 10
b = 20
def calculator():
  global a
  a = 20
  print(f"Addition of two numbers are: {a+b}" )

calculator()

Addition of two numbers are: 40


In [22]:
def outer():
  x = 5
  def inner():
    nonlocal x
    x = 10
    print("Inner function:", x)
  inner()
  print("Outer function x value is:", x)

outer()

Inner function: 10
Outer function x value is: 10


In [27]:
pip install numpy

In [28]:
import numpy as np

In [30]:
#python list and Numpy Array

py_list = [1,2,3,4,5]
np_array = np.array([1,2,3,4,5])

print(type(py_list))
print(type(np_array))

<class 'list'>
<class 'numpy.ndarray'>


In [31]:
#1D array

arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

#2D array
arr_2d = np.array([[1,2,3], #2x3 matrix
                   [4,5,6]])
print(arr_2d)

print(arr_2d.ndim)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
2


In [36]:
#arrays filled with zeros
zeros_array = np.zeros((2,3))
print(zeros_array)

#arrays filled with ones
zeros_array = np.ones((2,3))
print(zeros_array)

#arrays filles with nine
zeros_array = np.full((2,3),4)
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[4 4 4]
 [4 4 4]]


In [43]:
# array filles with evenly spaced values

linspace_array = np.linspace(1,10,5)
print(linspace_array)

#array filled with range of numbers

range_array = np.arange(1,10,2)
print(range_array)

#[2,20,10]
range_array = np.arange(2,20,10)
print(range_array)



[ 1.    3.25  5.5   7.75 10.  ]
[1 3 5 7 9]
[ 2 12]


In [44]:
def array_function(a,b,c):
  # array filles with evenly spaced values

  linspace_array = np.linspace(a,b,c)
  print(linspace_array)

  #array filled with range of numbers

  range_array = np.arange(a,b,c)
  print(range_array)

array_function(1,10,5)

[ 1.    3.25  5.5   7.75 10.  ]
[1 6]


In [48]:
#Create a random arrays

#array b/w 0 & 1
random_array = np.random.rand(3,3)
print(random_array)

#array b/w 1 & 99
random_array = np.random.randint(1,100,(3,3))
print(random_array.ndim)

[[0.79158546 0.52914074 0.34482817]
 [0.20268645 0.33760979 0.4343987 ]
 [0.57899056 0.49216271 0.64227538]]
2


In [50]:
#Shape, Size and Dimension of array

arr = np.array([[1,2,3],
                [3,4,5]])

print(arr.shape)
print(arr.size)

(2, 3)
6


In [51]:
#reshaping the arrays

arr = np.array([[1,2,3],
                [3,4,5]])

arr_reshaped = arr.reshape((3,2))
print(arr_reshaped)


[[1 2]
 [3 3]
 [4 5]]


In [52]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

print(arr1 + arr2)


[5 7 9]


In [59]:
#min, max, sum

arr = np.array([[1,2,3],
                [3,4,5]])

print(np.max(arr))
print(np.min(arr))
print(np.sum(arr))

5
1
18


In [60]:
#array indexing

arr = np.array([1,2,3,4,5])

print(arr[0])

1


In [64]:
#array indexing

arr = np.array([[1,2,3],
                [3,4,5]])

print(arr[-1,-1])

5


In [80]:
#slicing concept

arr1 = np.array([1,2,3,4,5])

print(arr1[::-1])

arr2 = np.array([[1,2,3],
                 [3,4,5],
                 [4,5,6]])

print(arr2[::-1,::-1])

[5 4 3 2 1]
[[6 5 4]
 [5 4 3]
 [3 2 1]]


In [81]:
#conditional filtering
arr1 = np.array([1,2,3,4,5])
result = np.where(arr1 > 2)
print(result)

print(arr1[arr1 > 2])

(array([2, 3, 4]),)
[3 4 5]


In [83]:
#np.take()

arr1 = np.array([1,2,3,4,5])
result = np.take(arr1, [0,2,4])
print(result)

np.put(arr1, [0,1], [10,20])

print(arr1)

[1 3 5]
[10 20  3  4  5]
